language: elixir

matrix:
  include:
    - otp_release: 18.3
      elixir: 1.3
    - otp_release: 19.3
      elixir: 1.3
    - otp_release: 18.3
      elixir: 1.4
    - otp_release: 19.3
      elixir: 1.4
    - otp_release: 20.2
      elixir: 1.4
    - otp_release: 19.3
      elixir: 1.5
    - otp_release: 20.2
      elixir: 1.5
    - otp_release: 20.2
      elixir: 1.6

env:
  GLOBAL:
    - MIX_ENV=test

sudo: false

after_script:
  - mix coveralls.travis
